name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Build
#      run: cargo build --verbose
#    - name: Run tests
#      run: cargo test --verbose
    - name: Build Lib
      run: cargo build --lib --verbose --release
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: gifski.dll
        path: /home/runner/work/gifski/gifski/target/release/gifski.dll
